description "Dogecoin2 Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env DOGECOIN2D_BIN="/usr/bin/dogecoin2d"
env DOGECOIN2D_USER="dogecoin2"
env DOGECOIN2D_GROUP="dogecoin2"
env DOGECOIN2D_PIDDIR="/var/run/dogecoin2d"
# upstart can't handle variables constructed with other variables
env DOGECOIN2D_PIDFILE="/var/run/dogecoin2d/dogecoin2d.pid"
env DOGECOIN2D_CONFIGFILE="/etc/dogecoin2/dogecoin2.conf"
env DOGECOIN2D_DATADIR="/var/lib/dogecoin2d"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # dogecoin2d will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$DOGECOIN2D_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run dogecoin2d."
        echo "The setting must appear in $DOGECOIN2D_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Dogecoin2 Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$DOGECOIN2D_PIDDIR"
    chmod 0755 "$DOGECOIN2D_PIDDIR"
    chown $DOGECOIN2D_USER:$DOGECOIN2D_GROUP "$DOGECOIN2D_PIDDIR"
    chown $DOGECOIN2D_USER:$DOGECOIN2D_GROUP "$DOGECOIN2D_CONFIGFILE"
    chmod 0660 "$DOGECOIN2D_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$DOGECOIN2D_PIDFILE" \
    --chuid $DOGECOIN2D_USER:$DOGECOIN2D_GROUP \
    --exec "$DOGECOIN2D_BIN" \
    -- \
    -pid="$DOGECOIN2D_PIDFILE" \
    -conf="$DOGECOIN2D_CONFIGFILE" \
    -datadir="$DOGECOIN2D_DATADIR" \
    -disablewallet \
    -daemon

